export const routes = {
    HOME: '/',
    LOGIN: '/login',
    MANAGERPARKING: "/parking-manager",
    ADMIN: '/admin',
    PARKING_DETAIL: "/parking-detail/:parkingID",
    PARKINGDETAIL: "/parking-detail/",
    PARKING_DETAIL_UPDATE: "/parking-detail/:parkingID/update",
    REGISTER: "/register",
    USERPROFILE: "/user-profile",
    MANAGEPARKINGMANAGER: "/manage-parking-manager",
    APPROVEPARKING:"/appreve-parking",
    MANAGECARMODEL: "/manage-carmodel",
    USER_PROFILE_UPDATE: "/user-profile/:id/update",
    MY_REQUEST: "/my-request",
    MY_CAR: "/my-car",
    MANAGE_REQUEST: "/manager-request",
}