name: Build and deploy .NET Core application to Web App BackendSWP490

env:
  AZURE_WEBAPP_NAME: BackendSWP490
  AZURE_WEBAPP_PACKAGE_NAME: '../published'   
  NETCORE_VERSION : 6.0.x

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up dotnet Core ${{ env.NETCORE_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.NETCORE_VERSION }}

      - name: Restore
        run: |
          cd Back-end
          dotnet restore
      - name: Build
        run: |
          cd Back-end
          dotnet build --no-restore
      - name: Update database
        run: |
          cd Back-end
          dotnet tool install --global dotnet-ef
          dotnet tool restore
          dotnet ef database update
        env:
          ASPNETCORE_ENVIRONMENT: Production
      - name: Publish
        run: |
          cd Back-end
          dotnet publish --configuration Release --output ${{ env.AZURE_WEBAPP_PACKAGE_NAME }}
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.BackendSWP490_9471 }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
